spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 1.5G
            limits:
              cpu: "0.4"
              memory: 2G
